version: '3.8'

services:
  spring-boot-postgre-sql:
    image: postgres:16
    container_name: spring-boot-postgre-sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-boot-postgre-sql
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: